version: '3.8'

services:
  server-registry:
#    image: eureka-server:latest
    build: ./Day27-Docker-ServerRegistry
    image: server-registry:latest
    container_name: server-registry
    ports:
      - "8761:8761"
    networks:
      - mysql_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/eureka/"]
      interval: 30s
      timeout: 10s
      retries: 5


#  mysql_banks:
#    image: mysql:latest
#    container_name: mysql-container-banks_db
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root  # Set the root password
#      MYSQL_DATABASE: banks_db
#      MYSQL_USER: mysql_banks  # Use a different username
#      MYSQL_PASSWORD: mysql_banks  # Use a different password
#    networks:
#      - mysql_network
#
#  mysql_customers:
#    image: mysql:latest
#    container_name: mysql-container-customers_db
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root  # Set the root password
#      MYSQL_DATABASE: customers_db
#      MYSQL_USER: mysql_customers  # Use a different username
#      MYSQL_PASSWORD: mysql_customers  # Use a different password
#    ports:
#      - "3308:3306"  # Change the host port to avoid conflict
#
#  mysql_vendors:
#   image: mysql:latest
#    container_name: mysql-container-vendors_db
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root  # Set the root password
#      MYSQL_DATABASE: vendors_db
#      MYSQL_USER: mysql_vendors  # Use a different username
#      MYSQL_PASSWORD: mysql_vendors  # Use a different password
#    ports:
#      - "3309:3306"  # Change the host port to avoid conflict
    

  config-server:
    build: ./Day27-Docker-ConfigServer
    image: config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
        server-registry:
            condition: service_healthy
    networks:
      - mysql_network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://server-registry:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      retries: 5
      start_period: 30s

  api-gateway:
    build: ./Day27-Docker-APIGateaway
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "9090:9090"
    networks:
      - mysql_network
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
    depends_on:
      config-server:
        condition: service_healthy
      server-registry:
        condition: service_healthy

  server-customer:
    build: ./Day27-Docker-WebClientCustomer
    image: server-customer:latest
    container_name: server-customer
    ports:
      - "6060:6060"
#    depends_on:
#      - api-gateway
#      - mysql-container-customers_db
    depends_on:
        api-gateway:
            condition: service_healthy
    networks:
      - mysql_network
#    environment:
#      - SPRING_APPLICATION_NAME=server-customer
#      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888/
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container-customers_db:3306/customers_db
#      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
#    eureka:
#    client:
#      service-url:
#        defaultZone: http://server-registry:8761/eureka/

  server-bank:
    build: ./Day27-Docker-WebClientBank
    image: server-bank:latest
    container_name: server-bank
    ports:
      - "6061:6061"
#    depends_on:
#      - api-gateway
#      - mysql-container-banks_db
    depends_on:
        api-gateway:
            condition: service_healthy
    networks:
      - mysql_network
#    environment:
#      - SPRING_APPLICATION_NAME=server-bank
#      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888/
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container-banks_db:3306/banks_db
#      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
#    eureka:
#    client:
#      service-url:
#        defaultZone: http://server-registry:8761/eureka/

  server-vendor:
    build: ./Day27-Docker-WebClientVendor
    image: server-vendor:latest
    container_name: server-vendor
    ports:
      - "6062:6062"
#    depends_on:
#      - api-gateway
#      - mysql-container-vendors_db
    depends_on:
        api-gateway:
            condition: service_healthy
    networks:
      - mysql_network
#    environment:
#      - SPRING_APPLICATION_NAME=server-vendor
#      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888/
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container-vendors_db:3306/vendors_db
#      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
#    eureka:
#    client:
#      service-url:
#        defaultZone: http://server-registry:8761/eureka/

networks:
  mysql_network:
#    external: true
    driver: bridge