spring.application.name=SERVER-CUSTOMER
spring.config.import=optional:configserver:http://localhost:8888/

server.port=8082

management.endpoints.web.exposure.include=*

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.cloud.config.uri=http://localhost:8888
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#logging.level.org.springframework=DEBUG
