# Use an OpenJDK base image
FROM openjdk:17-jdk

# Set working directory inside the container
WORKDIR /app

# Copy the built JAR file
COPY target/APIGateaway-3.2.6.jar api-gateaway.jar

# Expose the Eureka Server port
EXPOSE 8888

# Run the application
ENTRYPOINT ["java", "-jar", "api-gateaway.jar"]