server:
  port: 6060

spring:
  application:
    name: server-bank
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservices_db
      database: microservices_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/